// <auto-generated />
using System;
using DynamicAutomator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicAutomator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomationTaskDataSource", b =>
                {
                    b.Property<int>("DataSourcesId")
                        .HasColumnType("int");

                    b.Property<int>("TasksId")
                        .HasColumnType("int");

                    b.HasKey("DataSourcesId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("TaskDataSources", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.AutomationTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanvasJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("DelayAfterMs")
                        .HasColumnType("int");

                    b.Property<int>("DelayBeforeMs")
                        .HasColumnType("int");

                    b.Property<int>("DesignOrigin")
                        .HasColumnType("int");

                    b.Property<int?>("LastExecuteUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastExecutedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("UseGlobalDataSources")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ConditionType")
                        .HasColumnType("int");

                    b.Property<string>("ConstantEqualValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ContentSourceType")
                        .HasColumnType("int");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("DynamicSourceColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EqualityType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOr")
                        .HasColumnType("bit");

                    b.Property<string>("Navigation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SelectorId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConditionGroupId");

                    b.HasIndex("SelectorId");

                    b.HasIndex("SourceId");

                    b.ToTable("Conditions", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.ConditionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BreakLoopOnFailed")
                        .HasColumnType("bit");

                    b.Property<bool?>("BreakLoopOnSuccess")
                        .HasColumnType("bit");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<int?>("FailedGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<int?>("SuccessGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FailedGroupId");

                    b.HasIndex("StepId");

                    b.HasIndex("SuccessGroupId");

                    b.ToTable("ConditionGroups", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInsertable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMergable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopable")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DataSources", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.DataSourceCell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CellValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "RowIndex", "ColumnName");

                    b.ToTable("DataSourceCells", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("int");

                    b.Property<bool>("MoveLoop")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("SelectorId")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("SelectorId");

                    b.HasIndex("TaskId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Selector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApplyElementState")
                        .HasColumnType("bit");

                    b.Property<int?>("AttributeDataSourceId")
                        .HasColumnType("int");

                    b.Property<string>("AttributeDynamicColumn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AttributeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AttributeValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AttributeValueIsDynamic")
                        .HasColumnType("bit");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<string>("DynamicSourceColumnName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ElementBy")
                        .HasColumnType("int");

                    b.Property<bool>("ElementDisplayed")
                        .HasColumnType("bit");

                    b.Property<bool>("ElementEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("ElementSourceId")
                        .HasColumnType("int");

                    b.Property<string>("ElementValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FramePathJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAttribute")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInShadowRoot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndexDependent")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDuration")
                        .HasColumnType("int");

                    b.Property<int?>("MinDuration")
                        .HasColumnType("int");

                    b.Property<string>("ShadowSelector")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TryDelay")
                        .HasColumnType("int");

                    b.Property<int?>("TryTimes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementSourceId");

                    b.ToTable("Selectors", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConditional")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("GroupId");

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.StepAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int?>("ColumnsCount")
                        .HasColumnType("int");

                    b.Property<string>("ConstantValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ContentSourceType")
                        .HasColumnType("int");

                    b.Property<int?>("CopyFromId")
                        .HasColumnType("int");

                    b.Property<string>("DynamicSourceColumnName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FailedDelayBeforeRetry")
                        .HasColumnType("int");

                    b.Property<byte?>("FailedRetryTimes")
                        .HasColumnType("tinyint");

                    b.Property<string>("NavigateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OnFailedStepId")
                        .HasColumnType("int");

                    b.Property<int>("OnFailedType")
                        .HasColumnType("int");

                    b.Property<int>("RowIndexType")
                        .HasColumnType("int");

                    b.Property<int?>("SaveSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectorId")
                        .HasColumnType("int");

                    b.Property<int?>("WaitTimeDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaveSourceId");

                    b.HasIndex("SelectorId");

                    b.ToTable("Actions", (string)null);
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.UserTaskAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanModify")
                        .HasColumnType("bit");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "TaskId")
                        .IsUnique();

                    b.ToTable("UserTasks", (string)null);
                });

            modelBuilder.Entity("AutomationTaskDataSource", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DynamicAutomator.Domain.Entities.AutomationTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.AutomationTask", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.AppUser", "Creator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Condition", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.ConditionGroup", "ConditionGroup")
                        .WithMany("Conditions")
                        .HasForeignKey("ConditionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DynamicAutomator.Domain.Entities.Selector", "Selector")
                        .WithMany("Conditions")
                        .HasForeignKey("SelectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DynamicAutomator.Domain.Entities.DataSource", "Source")
                        .WithMany("Conditions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConditionGroup");

                    b.Navigation("Selector");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.ConditionGroup", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.Group", "FailedGroup")
                        .WithMany("FailedConditionGroups")
                        .HasForeignKey("FailedGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DynamicAutomator.Domain.Entities.Step", "Step")
                        .WithMany("ConditionGroups")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DynamicAutomator.Domain.Entities.Group", "SuccessGroup")
                        .WithMany("SuccessConditionGroups")
                        .HasForeignKey("SuccessGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FailedGroup");

                    b.Navigation("Step");

                    b.Navigation("SuccessGroup");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.DataSource", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.DataSourceCell", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.DataSource", "DataSource")
                        .WithMany("Cells")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Group", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.DataSource", "DataSource")
                        .WithMany("Groups")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DynamicAutomator.Domain.Entities.Group", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DynamicAutomator.Domain.Entities.Selector", "Selector")
                        .WithMany("Groups")
                        .HasForeignKey("SelectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DynamicAutomator.Domain.Entities.AutomationTask", "Task")
                        .WithMany("Groups")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("ParentGroup");

                    b.Navigation("Selector");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Selector", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.DataSource", "ElementSource")
                        .WithMany("Selectors")
                        .HasForeignKey("ElementSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ElementSource");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Step", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.StepAction", "Action")
                        .WithMany("Steps")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DynamicAutomator.Domain.Entities.Group", "Group")
                        .WithMany("Steps")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Action");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.StepAction", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.DataSource", "SaveSource")
                        .WithMany("Actions")
                        .HasForeignKey("SaveSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DynamicAutomator.Domain.Entities.Selector", "Selector")
                        .WithMany("Actions")
                        .HasForeignKey("SelectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SaveSource");

                    b.Navigation("Selector");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.UserTaskAccess", b =>
                {
                    b.HasOne("DynamicAutomator.Domain.Entities.AutomationTask", "Task")
                        .WithMany("UserAccess")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DynamicAutomator.Domain.Entities.AppUser", "User")
                        .WithMany("TaskAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("TaskAccess");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.AutomationTask", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.ConditionGroup", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.DataSource", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Cells");

                    b.Navigation("Conditions");

                    b.Navigation("Groups");

                    b.Navigation("Selectors");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Group", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("FailedConditionGroups");

                    b.Navigation("Steps");

                    b.Navigation("SuccessConditionGroups");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Selector", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.Step", b =>
                {
                    b.Navigation("ConditionGroups");
                });

            modelBuilder.Entity("DynamicAutomator.Domain.Entities.StepAction", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
